language: java
jdk: openjdk7

env:
  global:
  - TERM=dumb
  - secure: "EnoeJjBqPc/gnC83VOWrdnaWNFrrq1P4D4NVpu387tjVM6ejmutAvr0Pnx/hrPu1R8+RL23lFzPlvAGiPbneURQHEqZt47V2yXxOPxYp8oL74a5QGk420qCtDtiQTcbC6A0aheFk2UBmzIhddTfI3iyI78Tsghe9mMF+PUlXrVk="
  - secure: "HQFmxUk9nmy7MilybRAN0akVfw+8Thch1gnCzsE9qVqvICbxRhYmOHVULOAdlameeOUu4/DODZW4Rnlr+RrZEkwk49WLS70XkOfy0v9GliOqTkXaYZtzRoEnrjjIcboPkrG7nr25TB6AAjtFg/lpKtQ9UWY73Prs0/AVoWBLYIk="
  - secure: "BqO+9W0YAHPE2QdQFueEPszlJ/r/f7vpYAbHXHW38QIgpSEsk2LGKQpLXP07rlHnrMmF//bEwmGTK08pD6KpaIFFtgC20+9T5GiReMS0J6EH/vDHcZoZWDXInAFiDY/oK9DbHoJBvFXhrhQc8189lzKqDiFpIrlnOAsDgzXs4Ds="
  
branches:
  only:
  - master
  - develop

notifications:
  email: false
  irc: chat.freenode.net#syncany

before_install:
- sudo apt-get update
- sudo apt-get install -y -q lftp
- lftp -v

script:
- core/gradlew -Dos=linux -Darch=x86 pluginJar
- rm build/resources/main/org/syncany/plugins/gui/plugin.properties
- core/gradlew -Dos=linux -Darch=x86_64 pluginJar
- rm build/resources/main/org/syncany/plugins/gui/plugin.properties
- core/gradlew -Dos=windows -Darch=x86 pluginJar
- rm build/resources/main/org/syncany/plugins/gui/plugin.properties
- core/gradlew -Dos=windows -Darch=x86_64 pluginJar
- rm build/resources/main/org/syncany/plugins/gui/plugin.properties
- core/gradlew -Dos=macosx -Darch=x86 pluginJar
- rm build/resources/main/org/syncany/plugins/gui/plugin.properties
- core/gradlew -Dos=macosx -Darch=x86_64 pluginJar

after_success:
- core/gradle/lftp/lftpuploadplugin.sh

